# Generated by Django 4.1.1 on 2022-09-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_code_register_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Edad"
            ),
        ),
    ]
